### ISSUE TITLE
Choose sink via envrionment variable

### ISSUE THREAD

**Issue by cdupont** [telefonicaid/fiware-cygnus#1341]
Currently it is not possible to choose which sink you want through environment variable only.
I would like to start Cygnus like this, using only the default Mongo sink:

```
cygnus:
     image: fiware/cygnus-ngsi:latest
     links:
       - orion
       - mongo
     environment:
       - CYGNUS_NGSI_SINKS=mongo
     ports:
       - "8081:8081"
       - "5050:5050"
```
