### ISSUE TITLE
docker image cygnus-ngsi overwrites agent.conf

### ISSUE THREAD

**Issue by mausquirk** [telefonicaid/fiware-cygnus#1496]
The mechanism to mount the configuration file into the docker-container does not work as described in the [documentation](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/installation_and_administration_guide/install_with_docker.md#using-volumes).

The agent.conf files gets overwritten when restarting the docker container by the [cygnus-entrypoint.sh-script.](https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L25)
My docker-compose: 
```
version: '2.2'
  
services:
  cygnus: 
    image: fiware/cygnus-ngsi
    links:
      - mongodb
    ports:
      - "5050:5050"   
    volumes:
      - ./data/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf 
```
What's broken? The documentation or the Docker's cygnus-entrypoint.sh-script?
