### ISSUE TITLE
Error when using Atlas

### ISSUE THREAD

**Issue by Choi-JongMoon** [telefonicaid/fiware-cygnus#1900]
Hi im really interested in FIWARE project, especially Cygnus
But, I faced this problem.
I use Atlas MongoDB and I finished installing context Broker, Orion, and checked out saving into DB.
And then using docker, there is an error.

- docker-compose.yml
```
version: "3"

services:
  cygnus:
    container_name: cygnus
    image: fiware/cygnus-ngsi:2.3.0
    ports:
      - "5051:5051"
      - "8081:8081"
    environment:
      - "CYGNUS_MONGO_HOSTS=cluster0-shard-00-00.xxxxx.mongodb.net:27017,cluster0-shard-00-01.xxxxx.mongodb.net:27017,cluster0-shard-00-02.xxxxx.mongodb.net:27017"
      - "CYGNUS_MONGO_USER=<user>"
      - "CYGNUS_MONGO_PASS=<password>"
      - "CYGNUS_MONGO_AUTH_SOURCE=admin"
```
LOG
> time=2020-07-21T16:07:18.501Z | lvl=WARN | corr=1bf39fc8-cb6c-11ea-9e57-0242ac140002 | trans=e4f69804-ea5b-4318-9a05-53059ba9a1b2 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=createCollection | msg=com.telefonica.iot.cygnus.backends.mongo.MongoBackendImpl[130] : Error in collection sth_/_raspberrypi:001_RaspberryPi.aggr creating index ex=Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=cluster0-shard-00-02.hydoh.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=cluster0-shard-00-00.hydoh.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=cluster0-shard-00-01.hydoh.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]

It seems "type=UNKNOWN problem".
I think the additional preference is the problem.
In Orion context Broker, there are several command option like
``` -rplSet  -dbAuthDb -dbSSL ```

But there is no rplicaSet, SSL in Cygnus Project.

How can I solve these problems?
