### ISSUE TITLE
Difference between the order of indexes and the order of data registered in MongoDB

### ISSUE THREAD

**Issue by ctc-watanabe** [telefonicaid/fiware-cygnus#2246]
Hi, I would like to know about the order of indexes and data by NGSIMongoSINK.

The indexes created in MongoDB have changed since Cygnus 3.0.0, but they differ from the order of the columns of data registered by NGSIMongoSINK.

The indexes created since version 3 are as follows:

```
> db['sth_/_Car1_Car'].getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_"
        },
        {
                "v" : 2,
                "key" : {
                        "recvTime" : 1,
                        "attrName" : 1,
                        "attrType" : 1,
                        "attrValue" : 1
                },
                "name" : "cyg_raw_opt"
        }
]
```

However, the data registered in MongoDB are as follows:

```
> db['sth_/_Car1_Car'].find()
{ "_id" : ObjectId("64794d75307d1229f47779b4"), "attrName" : "speed", "attrType" : "Float", "attrValue" : 70, "recvTime" : ISODate("2023-06-02T02:01:24.136Z") }
{ "_id" : ObjectId("64794d77307d1229f47779b5"), "attrName" : "speed", "attrType" : "Float", "attrValue" : 80, "recvTime" : ISODate("2023-06-02T02:01:27.278Z") }
```

In MongoDB, if the column order of the index and data is different, the index will not work.

I am using docker to verify this and docker-compose.yml is as follows:

```
version: "3"

services:
  orion:
    container_name: orion
    image: fiware/orion:3.7.0
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG

  cygnus:
    container_name: cygnus
    image: fiware/cygnus-ngsi:3.1.0 # Docker image built from branch 3.1.0
    links:
      - mongo
    expose:
      - "5080"
    ports:
      - "5051:5051"
      - "5080:5080"
    environment:
      - CYGNUS_MONGO_HOSTS=mongo:27017
      - CYGNUS_API_PORT=5080

  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
```

Could you tell me if my configuration is not enough or if it is a bug?

If there is a setting that changes the order of the data, I would like to know.

Thank you in advance.
